// frontend-react/src/features/courses/CourseList.tsx
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useNavigate } from 'react-router-dom';
import { Eye, Pencil, Trash2 } from 'lucide-react';

import { courseService } from '@/api/courseService';
import { departmentService } from '@/api/departmentService';
import { useAuth } from '@/features/auth/AuthContext';
import { useToast } from '@/components/Toast';
import { PageHeader } from '@/components/PageHeader';
import { DataTable, Column } from '@/components/DataTable';
import { Modal } from '@/components/Modal';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { StatusBadge } from '@/components/StatusBadge';
import { FormInput } from '@/components/FormInput';
import { FormSelect } from '@/components/FormSelect';

const courseSchema = z.object({
  name: z.string().min(2, 'Name is required'),
  code: z.string().min(2, 'Code is required'),
  description: z.string().optional(),
  departmentId: z.coerce.number().min(1, 'Department is required'),
  durationYears: z.coerce.number().min(1, 'Duration is required'),
  totalSemesters: z.coerce.number().min(1, 'Total Semesters is required'),
  degreeType: z.enum(['BACHELOR', 'MASTER', 'DIPLOMA', 'DOCTORATE']),
  isActive: z.boolean().default(true),
});

type CourseFormValues = z.infer<typeof courseSchema>;

export const CourseList: React.FC = () => {
  const { hasAnyRole } = useAuth() as any;
  const toast = useToast();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isAdmin = hasAnyRole(['SUPER_ADMIN', 'ADMIN']);

  const [page, setPage] = useState(0);
  const [size] = useState(10);
  const [departmentId, setDepartmentId] = useState<number | undefined>();
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  const [selectedCourse, setSelectedCourse] = useState<any>(null);

  const { data, isLoading } = useQuery({
    queryKey: ['courses', page, size, departmentId],
    queryFn: () => courseService.getAll({ page, size, departmentId }),
  });

  const { data: deptRes } = useQuery({
    queryKey: ['departmentsForSelect'],
    queryFn: () => departmentService.getAll({ page: 0, size: 100 }),
  });

  const { register, handleSubmit, reset, formState: { errors } } = useForm<CourseFormValues>({
    resolver: zodResolver(courseSchema),
  });

  const createMutation = useMutation({
    mutationFn: (data: CourseFormValues) => courseService.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['courses'] });
      toast.success('Course created');
      setIsModalOpen(false);
      reset();
    },
    onError: () => toast.error('Failed to create course'),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: CourseFormValues }) => courseService.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['courses'] });
      toast.success('Course updated');
      setIsModalOpen(false);
      reset();
    },
    onError: () => toast.error('Failed to update course'),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => courseService.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['courses'] });
      toast.success('Course deleted');
      setIsDeleteModalOpen(false);
    },
    onError: () => toast.error('Failed to delete course'),
  });

  const onSubmit = (formData: CourseFormValues) => {
    if (selectedCourse) updateMutation.mutate({ id: selectedCourse.id, data: formData });
    else createMutation.mutate(formData);
  };

  const columns: Column<any>[] = [
    { header: 'Code', accessor: 'code' },
    { header: 'Name', accessor: 'name' },
    { header: 'Department', accessor: 'departmentName' },
    { header: 'Status', accessor: 'isActive', render: (item) => <StatusBadge status={item.isActive ? 'ACTIVE' : 'INACTIVE'} /> },
    { header: 'Actions', accessor: 'id', render: (item) => (
        <div className="flex space-x-2">
          <button onClick={() => navigate(`/courses/${item.id}`)} className="text-blue-600"><Eye size={18} /></button>
          {isAdmin && (
            <>
              <button onClick={() => { setSelectedCourse(item); reset(item); setIsModalOpen(true); }} className="text-yellow-600"><Pencil size={18} /></button>
              <button onClick={() => { setSelectedCourse(item); setIsDeleteModalOpen(true); }} className="text-red-600"><Trash2 size={18} /></button>
            </>
          )}
        </div>
      )
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Courses" action={isAdmin ? <button className="px-4 py-2 bg-blue-600 text-white rounded-md" onClick={() => { setSelectedCourse(null); reset({}); setIsModalOpen(true); }}>Add Course</button> : undefined} />
      
      <div className="bg-white p-4 rounded-lg shadow-sm border">
        <select 
          className="w-full md:w-1/3 p-2 border rounded-md"
          value={departmentId || ''}
          onChange={(e) => setDepartmentId(e.target.value ? Number(e.target.value) : undefined)}
        >
          <option value="">All Departments</option>
          {deptRes?.data?.content?.map((d: any) => <option key={d.id} value={d.id}>{d.name}</option>)}
        </select>
      </div>

      <DataTable columns={columns} data={data?.data?.content || []} loading={isLoading} page={page} totalPages={data?.data?.totalPages || 0} onPageChange={setPage} />

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={selectedCourse ? 'Edit Course' : 'Add Course'}>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <FormInput label="Name" {...register('name')} error={errors.name?.message} />
          <FormInput label="Code" {...register('code')} error={errors.code?.message} />
          <FormSelect label="Department" {...register('departmentId')} error={errors.departmentId?.message} options={deptRes?.data?.content?.map((d: any) => ({ value: d.id, label: d.name })) || []} />
          <FormSelect label="Degree Type" {...register('degreeType')} error={errors.degreeType?.message} options={[{value: 'BACHELOR', label: 'Bachelor'}, {value: 'MASTER', label: 'Master'}, {value: 'DIPLOMA', label: 'Diploma'}, {value: 'DOCTORATE', label: 'Doctorate'}]} />
          <div className="grid grid-cols-2 gap-4">
            <FormInput label="Duration (Years)" type="number" {...register('durationYears')} error={errors.durationYears?.message} />
            <FormInput label="Total Semesters" type="number" {...register('totalSemesters')} error={errors.totalSemesters?.message} />
          </div>
          <FormInput label="Description" {...register('description')} error={errors.description?.message} />
          <div className="flex items-center mt-4">
            <input type="checkbox" id="isActive" {...register('isActive')} className="mr-2" />
            <label htmlFor="isActive" className="ml-2">Is Active</label>
          </div>
          <div className="flex justify-end space-x-2">
            <button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 border rounded-md">Cancel</button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded-md">Save</button>
          </div>
        </form>
      </Modal>

      <ConfirmDialog isOpen={isDeleteModalOpen} title="Delete Course" message="Are you sure?" onConfirm={() => deleteMutation.mutate(selectedCourse?.id)} onClose={() => setIsDeleteModalOpen(false)} variant="danger" />
    </div>
  );
};

// frontend-angular/src/app/features/courses/course-list/course-list.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { CourseService } from '../../../core/services/course.service';
import { DepartmentService } from '../../../core/services/department.service';
import { AuthService } from '../../../core/services/auth.service';
import { CourseResponse, DepartmentSummaryResponse } from '../../../core/models/models';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { DataTableComponent } from '../../../shared/components/data-table/data-table.component';
import { ModalComponent } from '../../../shared/components/modal/modal.component';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { finalize } from 'rxjs';

@Component({
  selector: 'app-course-list',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, PageHeaderComponent, DataTableComponent, ModalComponent, ConfirmDialogComponent, StatusBadgeComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Courses"   (actionClicked)="openCreateModal()"></app-page-header>
      
      <div class="mt-6 bg-white rounded-lg shadow">
        <app-data-table [columns]="columns" [data]="courses()" [totalElements]="0" [loading]="loading()" (pageChange)="onPageChange($event)" >
          <ng-template #cellTemplate let-col let-item>
            <ng-container *ngIf="col.key === 'status'"><app-status-badge [status]="item.isActive ? 'ACTIVE' : 'INACTIVE'"></app-status-badge></ng-container>
            <ng-container *ngIf="col.key === 'actions'">
              <div class="flex space-x-2">
                <a [routerLink]="['/courses', item.id]" class="text-blue-600 hover:text-blue-900">View</a>
                <button *ngIf="isAdminOrDean()" (click)="openEditModal(item)" class="text-indigo-600 hover:text-indigo-900 ml-2">Edit</button>
                <button *ngIf="isAdminOrDean()" (click)="openDeleteConfirm(item)" class="text-red-600 hover:text-red-900 ml-2">Delete</button>
              </div>
            </ng-container>
            <ng-container *ngIf="col.key !== 'status' && col.key !== 'actions'">{{ item[col.key] }}</ng-container>
          </ng-template>
        </app-data-table>
      </div>

      <app-modal [isOpen]="isModalOpen()" [title]="isEditing() ? 'Edit Course' : 'Add Course'" (close)="closeModal()">
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4 p-4">
          <div><label class="block text-sm font-medium text-gray-700">Code</label><input type="text" formControlName="code" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm"></div>
          <div><label class="block text-sm font-medium text-gray-700">Name</label><input type="text" formControlName="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm"></div>
          <div><label class="block text-sm font-medium text-gray-700">Description</label><textarea formControlName="description" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm"></textarea></div>
          <div><label class="block text-sm font-medium text-gray-700">Department</label>
            <select formControlName="departmentId" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm">
              <option *ngFor="let dept of departments()" [value]="dept.id">{{ dept.name }}</option>
            </select>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">Duration (Years)</label><input type="number" formControlName="durationYears" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm"></div>
            <div><label class="block text-sm">Total Semesters</label><input type="number" formControlName="totalSemesters" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm"></div>
          </div>
          <div><label class="block text-sm font-medium text-gray-700">Degree Type</label>
            <select formControlName="degreeType" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm">
              <option value="BACHELOR">BACHELOR</option><option value="MASTER">MASTER</option><option value="DIPLOMA">DIPLOMA</option><option value="DOCTORATE">DOCTORATE</option>
            </select>
          </div>
          <div class="flex items-center"><input type="checkbox" formControlName="isActive" class="h-4 w-4 text-indigo-600 border-gray-300 rounded"><label class="ml-2 block text-sm text-gray-900">Active</label></div>
          <div class="mt-5 sm:mt-6 sm:flex sm:flex-row-reverse">
            <button type="submit" [disabled]="form.invalid || submitting()" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none sm:ml-3 sm:w-auto sm:text-sm">Save</button>
            <button type="button" (click)="closeModal()" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none sm:mt-0 sm:w-auto sm:text-sm">Cancel</button>
          </div>
        </form>
      </app-modal>

      <app-confirm-dialog [isOpen]="isConfirmOpen()" title="Delete Course" message="Are you sure you want to delete this course?" confirmText="Delete" cancelText="Cancel" (confirm)="deleteCourse()" (cancel)="closeConfirm()"></app-confirm-dialog>
    </div>
  `
})
export class CourseListComponent implements OnInit {
  private courseService = inject(CourseService);
  private deptService = inject(DepartmentService);
  private authService = inject(AuthService);
  private fb = inject(FormBuilder);

  courses = signal<CourseResponse[]>([]);
  departments = signal<DepartmentSummaryResponse[]>([]);
  totalElements = signal<number>(0);
  loading = signal<boolean>(false);
  submitting = signal<boolean>(false);
  
  isModalOpen = signal<boolean>(false);
  isConfirmOpen = signal<boolean>(false);
  isEditing = signal<boolean>(false);
  selectedCourse = signal<CourseResponse | null>(null);

  currentPage = 0;
  pageSize = 10;
  searchQuery = '';

  columns = [
    { key: 'code', label: 'Code' },
    { key: 'name', label: 'Name' },
    { key: 'departmentName', label: 'Department' },
    { key: 'status', label: 'Status' },
    { key: 'actions', label: 'Actions' }
  ];

  form: FormGroup = this.fb.group({
    code: ['', Validators.required],
    name: ['', Validators.required],
    description: [''],
    departmentId: [null, Validators.required],
    durationYears: [null, Validators.required],
    totalSemesters: [null, Validators.required],
    degreeType: ['BACHELOR', Validators.required],
    isActive: [true]
  });

  isAdminOrDean = signal<boolean>(false);

  ngOnInit() {
    this.isAdminOrDean.set(this.authService.hasAnyRole(['ROLE_SUPER_ADMIN', 'ROLE_ADMIN', 'ROLE_DEAN']));
    this.loadData();
    this.deptService.getAll(0, 100).subscribe(res => this.departments.set(res.content));
  }

  loadData() {
    this.loading.set(true);
    this.courseService.getAll(this.currentPage, this.pageSize).pipe(
      finalize(() => this.loading.set(false))
    ).subscribe({
      next: (response) => {
        let content = response.content;
        if (this.searchQuery) {
          content = content.filter(c => c.name.toLowerCase().includes(this.searchQuery.toLowerCase()) || c.code.toLowerCase().includes(this.searchQuery.toLowerCase()));
        }
        this.courses.set(content as any);
        this.totalElements.set(response.totalElements);
      }
    });
  }

  onPageChange(page: number) { this.currentPage = page; this.loadData(); }
  onSearch(query: string) { this.searchQuery = query; this.currentPage = 0; this.loadData(); }

  openCreateModal() { this.isEditing.set(false); this.form.reset({degreeType: 'BACHELOR', isActive: true}); this.isModalOpen.set(true); }
  openEditModal(course: CourseResponse) { this.isEditing.set(true); this.selectedCourse.set(course); this.form.patchValue(course); this.isModalOpen.set(true); }
  closeModal() { this.isModalOpen.set(false); }

  openDeleteConfirm(course: CourseResponse) { this.selectedCourse.set(course); this.isConfirmOpen.set(true); }
  closeConfirm() { this.isConfirmOpen.set(false); }

  onSubmit() {
    if (this.form.invalid) return;
    this.submitting.set(true);
    const request = this.form.value;
    
    const obs = this.isEditing() ? this.courseService.update(this.selectedCourse()!.id, request) : this.courseService.create(request);
    obs.pipe(finalize(() => this.submitting.set(false))).subscribe({
      next: () => { this.closeModal(); this.loadData(); }
    });
  }

  deleteCourse() {
    const id = this.selectedCourse()?.id;
    if (id) {
      this.courseService.delete(id).subscribe({ next: () => { this.closeConfirm(); this.loadData(); } });
    }
  }
}
