// frontend-react/src/features/students/StudentDetail.tsx
import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft } from 'lucide-react';
import { studentService } from '@/api/studentService';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { StatusBadge } from '@/components/StatusBadge';

export const StudentDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState<'profile' | 'guardians' | 'enrollments'>('profile');

  const { data: res, isLoading } = useQuery({
    queryKey: ['student', id],
    queryFn: () => studentService.getById(Number(id)),
    enabled: !!id,
  });

  const { data: envRes, isLoading: enrollmentsLoading } = useQuery({
    queryKey: ['studentEnrollments', id],
    queryFn: () => studentService.getEnrollments(Number(id)),
    enabled: !!id && activeTab === 'enrollments',
  });

  if (isLoading) return <LoadingSpinner />;
  const student = res?.data;
  if (!student) return <div>Student not found</div>;
  const enrollments = envRes?.data || [];

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-4 mb-4">
        <button onClick={() => navigate('/students')} className="p-2 hover:bg-gray-100 rounded-full">
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-2xl font-bold flex-1">{student.firstName} {student.lastName}</h1>
        <StatusBadge status={student.status as any} />
      </div>

      <div className="bg-white rounded-lg shadow-sm border overflow-hidden">
        <div className="flex border-b">
          <button className={`px-6 py-3 font-medium ${activeTab === 'profile' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-gray-500 hover:text-gray-700'}`} onClick={() => setActiveTab('profile')}>Profile</button>
          <button className={`px-6 py-3 font-medium ${activeTab === 'guardians' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-gray-500 hover:text-gray-700'}`} onClick={() => setActiveTab('guardians')}>Guardians</button>
          <button className={`px-6 py-3 font-medium ${activeTab === 'enrollments' ? 'border-b-2 border-blue-600 text-blue-600' : 'text-gray-500 hover:text-gray-700'}`} onClick={() => setActiveTab('enrollments')}>Enrollments</button>
        </div>

        <div className="p-6">
          {activeTab === 'profile' && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              <div><p className="text-sm text-gray-500">Roll Number</p><p className="font-medium">{student.rollNumber}</p></div>
              <div><p className="text-sm text-gray-500">Registration Number</p><p className="font-medium">{student.registrationNumber}</p></div>
              <div><p className="text-sm text-gray-500">Email</p><p className="font-medium">{student.email}</p></div>
              <div><p className="text-sm text-gray-500">Phone</p><p className="font-medium">{student.phone}</p></div>
              <div><p className="text-sm text-gray-500">Department ID</p><p className="font-medium">{student.departmentId}</p></div>
              <div><p className="text-sm text-gray-500">Course ID</p><p className="font-medium">{student.courseId}</p></div>
              <div><p className="text-sm text-gray-500">Current Semester</p><p className="font-medium">{student.currentSemester}</p></div>
              <div><p className="text-sm text-gray-500">Batch Year</p><p className="font-medium">{student.batchYear}</p></div>
              <div><p className="text-sm text-gray-500">Gender</p><p className="font-medium">{student.gender}</p></div>
            </div>
          )}
          
          {activeTab === 'guardians' && (
            <div>
              <h3 className="text-lg font-medium mb-4">Guardians</h3>
              <p className="text-gray-500">No guardians listed yet.</p>
            </div>
          )}

          {activeTab === 'enrollments' && (
            <div>
              <div className="flex justify-between items-center mb-4">
                <h3 className="text-lg font-medium">Enrolled Subjects</h3>
                <button className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm">Enroll in Subject</button>
              </div>
              {enrollmentsLoading ? <LoadingSpinner /> : (
                enrollments.length ? (
                  <ul className="divide-y border rounded-md">
                    {enrollments.map((env: any) => (
                      <li key={env.id} className="p-4 flex justify-between items-center">
                        <div>
                          <p className="font-medium">Subject ID: {env.subjectId}</p>
                          <p className="text-sm text-gray-500">Academic Year: {env.academicYear}</p>
                        </div>
                        <StatusBadge status={env.status as any} />
                      </li>
                    ))}
                  </ul>
                ) : <p className="text-gray-500">No enrollments found.</p>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// frontend-angular/src/app/features/students/student-detail/student-detail.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { StudentService } from '../../../core/services/student.service';
import { StudentResponse, EnrollmentResponse } from '../../../core/models/models';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';

@Component({
  selector: 'app-student-detail',
  standalone: true,
  imports: [CommonModule, RouterModule, PageHeaderComponent, StatusBadgeComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Student Details"  ></app-page-header>
      
      <div *ngIf="student()" class="mt-6 bg-white shadow rounded-lg overflow-hidden">
        <div class="px-4 py-5 sm:px-6 flex justify-between items-center border-b border-gray-200">
          <div><h3 class="text-lg leading-6 font-medium text-gray-900">{{ student()?.firstName }} {{ student()?.lastName }}</h3><p class="mt-1 max-w-2xl text-sm text-gray-500">Roll No: {{ student()?.rollNumber }} | Reg No: {{ student()?.registrationNumber }}</p></div>
          <app-status-badge [status]="student()!.status"></app-status-badge>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
          <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Department</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ student()?.departmentName }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Course</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ student()?.courseName }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Current Semester</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ student()?.currentSemester }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Email</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ student()?.email }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Phone</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ student()?.phone }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Admission Date</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ student()?.admissionDate }}</dd></div>
          </dl>
        </div>
      </div>
      
      <div class="mt-8">
        <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">Enrollments</h3>
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <ul role="list" class="divide-y divide-gray-200">
            <li *ngFor="let enrollment of enrollments()">
              <div class="px-4 py-4 sm:px-6"><div class="flex items-center justify-between"><p class="text-sm font-medium text-indigo-600 truncate">{{ enrollment.subjectName }} ({{ enrollment.subjectCode }})</p><app-status-badge [status]="enrollment.status"></app-status-badge></div><div class="mt-2 sm:flex sm:justify-between"><div class="sm:flex"><p class="flex items-center text-sm text-gray-500">Sem: {{ enrollment.semester }} | Academic Year: {{ enrollment.academicYear }}</p></div></div></div>
            </li>
            <li *ngIf="enrollments().length === 0" class="px-4 py-4 sm:px-6 text-sm text-gray-500">No enrollments found.</li>
          </ul>
        </div>
      </div>
    </div>
  `
})
export class StudentDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private studentService = inject(StudentService);

  student = signal<StudentResponse | null>(null);
  enrollments = signal<EnrollmentResponse[]>([]);

  ngOnInit() {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (id) {
      this.studentService.getById(id).subscribe(s => this.student.set(s));
      this.studentService.getEnrollments(id).subscribe(e => this.enrollments.set(e));
    }
  }
}
