// frontend-angular/src/app/features/courses/course-detail/course-detail.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { CourseService } from '../../../core/services/course.service';
import { SubjectService } from '../../../core/services/subject.service';
import { CourseResponse, SubjectSummaryResponse } from '../../../core/models/models';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';

@Component({
  selector: 'app-course-detail',
  standalone: true,
  imports: [CommonModule, RouterModule, PageHeaderComponent, StatusBadgeComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Course Details"  ></app-page-header>
      
      <div *ngIf="course()" class="mt-6 bg-white shadow rounded-lg overflow-hidden">
        <div class="px-4 py-5 sm:px-6 flex justify-between items-center border-b border-gray-200">
          <div><h3 class="text-lg leading-6 font-medium text-gray-900">{{ course()?.name }}</h3><p class="mt-1 max-w-2xl text-sm text-gray-500">Code: {{ course()?.code }} | Dept: {{ course()?.departmentName }}</p></div>
          <app-status-badge [status]="course()!.isActive ? 'ACTIVE' : 'INACTIVE'"></app-status-badge>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
          <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Description</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ course()?.description }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Duration</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ course()?.durationYears }} Years</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Total Semesters</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ course()?.totalSemesters }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Degree Type</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ course()?.degreeType }}</dd></div>
          </dl>
        </div>
      </div>
      
      <div class="mt-8">
        <h3 class="text-lg leading-6 font-medium text-gray-900 mb-4">Subjects</h3>
        <div class="bg-white shadow overflow-hidden sm:rounded-md">
          <ul role="list" class="divide-y divide-gray-200">
            <li *ngFor="let subject of subjects()">
              <a [routerLink]="['/subjects', subject.id]" class="block hover:bg-gray-50"><div class="px-4 py-4 sm:px-6"><div class="flex items-center justify-between"><p class="text-sm font-medium text-indigo-600 truncate">{{ subject.name }}</p><p class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-blue-100 text-blue-800">Sem {{ subject.semester }}</p></div><div class="mt-2 sm:flex sm:justify-between"><div class="sm:flex"><p class="flex items-center text-sm text-gray-500">Code: {{ subject.code }} | Credits: {{ subject.credits }}</p></div></div></div></a>
            </li>
            <li *ngIf="subjects().length === 0" class="px-4 py-4 sm:px-6 text-sm text-gray-500">No subjects found.</li>
          </ul>
        </div>
      </div>
    </div>
  `
})
export class CourseDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private courseService = inject(CourseService);
  private subjectService = inject(SubjectService);

  course = signal<CourseResponse | null>(null);
  subjects = signal<SubjectSummaryResponse[]>([]);

  ngOnInit() {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (id) {
      this.courseService.getById(id).subscribe(c => this.course.set(c));
      (this.subjectService as any).getByCourse(id).subscribe((s: any) => this.subjects.set(s));
    }
  }
}

// frontend-react/src/features/courses/CourseDetail.tsx
import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft } from 'lucide-react';
import { courseService } from '@/api/courseService';
import { subjectService } from '@/api/subjectService';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { StatusBadge } from '@/components/StatusBadge';

export const CourseDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const { data: res, isLoading } = useQuery({
    queryKey: ['course', id],
    queryFn: () => courseService.getById(Number(id)),
    enabled: !!id,
  });

  const { data: subRes, isLoading: subjectsLoading } = useQuery({
    queryKey: ['courseSubjects', id],
    queryFn: () => subjectService.getAll({ courseId: Number(id), page: 0, size: 100 }),
    enabled: !!id,
  });

  if (isLoading) return <LoadingSpinner />;
  const course = res?.data;
  if (!course) return <div>Course not found</div>;
  const subjects = subRes?.data?.content || [];

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-4 mb-4">
        <button onClick={() => navigate('/courses')} className="p-2 hover:bg-gray-100 rounded-full">
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-2xl font-bold flex-1">{course.name}</h1>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-sm border">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div><p className="text-sm text-gray-500">Code</p><p className="font-medium">{course.code}</p></div>
          <div><p className="text-sm text-gray-500">Department ID</p><p className="font-medium">{course.departmentId}</p></div>
          <div><p className="text-sm text-gray-500">Degree Type</p><p className="font-medium">{course.degreeType}</p></div>
          <div><p className="text-sm text-gray-500">Duration (Years)</p><p className="font-medium">{course.durationYears}</p></div>
          <div><p className="text-sm text-gray-500">Total Semesters</p><p className="font-medium">{course.totalSemesters}</p></div>
          <div><p className="text-sm text-gray-500">Status</p><StatusBadge status={course.isActive ? 'ACTIVE' : 'INACTIVE'} /></div>
          <div className="md:col-span-2 lg:col-span-3"><p className="text-sm text-gray-500">Description</p><p className="font-medium">{course.description}</p></div>
        </div>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-sm border mt-6">
        <h2 className="text-lg font-semibold mb-4">Subjects in Course</h2>
        {subjectsLoading ? <LoadingSpinner /> : (
          subjects.length ? (
            <ul className="divide-y">
              {subjects.map((sub: any) => (
                <li key={sub.id} className="py-3 flex justify-between items-center">
                  <div>
                    <p className="font-medium">{sub.name}</p>
                    <p className="text-sm text-gray-500">{sub.code} - Sem {sub.semester}</p>
                  </div>
                  <StatusBadge status={sub.isActive ? 'ACTIVE' : 'INACTIVE'} />
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-gray-500">No subjects found for this course.</p>
          )
        )}
      </div>
    </div>
  );
};
