// frontend-react/src/features/professors/ProfessorDetail.tsx
import React from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { ArrowLeft } from 'lucide-react';
import { professorService } from '@/api/professorService';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { StatusBadge } from '@/components/StatusBadge';

export const ProfessorDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const { data: res, isLoading } = useQuery({
    queryKey: ['professor', id],
    queryFn: () => professorService.getById(Number(id)),
    enabled: !!id,
  });

  if (isLoading) return <LoadingSpinner />;
  const prof = res?.data;
  if (!prof) return <div>Professor not found</div>;

  return (
    <div className="space-y-6">
      <div className="flex items-center space-x-4 mb-4">
        <button onClick={() => navigate('/professors')} className="p-2 hover:bg-gray-100 rounded-full">
          <ArrowLeft size={20} />
        </button>
        <h1 className="text-2xl font-bold flex-1">{prof.firstName} {prof.lastName}</h1>
      </div>

      <div className="bg-white p-6 rounded-lg shadow-sm border">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <div><p className="text-sm text-gray-500">Employee ID</p><p className="font-medium">{prof.employeeId}</p></div>
          <div><p className="text-sm text-gray-500">Email</p><p className="font-medium">{prof.email}</p></div>
          <div><p className="text-sm text-gray-500">Phone</p><p className="font-medium">{prof.phone}</p></div>
          <div><p className="text-sm text-gray-500">Department ID</p><p className="font-medium">{prof.departmentId}</p></div>
          <div><p className="text-sm text-gray-500">Designation</p><p className="font-medium">{prof.designation}</p></div>
          <div><p className="text-sm text-gray-500">Qualification</p><p className="font-medium">{prof.qualification}</p></div>
          <div><p className="text-sm text-gray-500">Specialization</p><p className="font-medium">{prof.specialization}</p></div>
          <div><p className="text-sm text-gray-500">Joining Date</p><p className="font-medium">{prof.joiningDate}</p></div>
          <div><p className="text-sm text-gray-500">Status</p><StatusBadge status={prof.status as any} /></div>
        </div>
      </div>
    </div>
  );
};

// frontend-angular/src/app/features/professors/professor-detail/professor-detail.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, RouterModule } from '@angular/router';
import { ProfessorService } from '../../../core/services/professor.service';
import { ProfessorResponse } from '../../../core/models/models';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';

@Component({
  selector: 'app-professor-detail',
  standalone: true,
  imports: [CommonModule, RouterModule, PageHeaderComponent, StatusBadgeComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Professor Details"  ></app-page-header>
      
      <div *ngIf="professor()" class="mt-6 bg-white shadow rounded-lg overflow-hidden">
        <div class="px-4 py-5 sm:px-6 flex justify-between items-center border-b border-gray-200">
          <div><h3 class="text-lg leading-6 font-medium text-gray-900">{{ professor()?.firstName }} {{ professor()?.lastName }}</h3><p class="mt-1 max-w-2xl text-sm text-gray-500">Employee ID: {{ professor()?.employeeId }}</p></div>
          <app-status-badge [status]="professor()!.status"></app-status-badge>
        </div>
        <div class="border-t border-gray-200 px-4 py-5 sm:p-0">
          <dl class="sm:divide-y sm:divide-gray-200">
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Department</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.departmentName }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Designation</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.designation }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Email</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.email }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Phone</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.phone }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Qualification</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.qualification }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Specialization</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.specialization }}</dd></div>
            <div class="py-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6"><dt class="text-sm font-medium text-gray-500">Joining Date</dt><dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">{{ professor()?.joiningDate }}</dd></div>
          </dl>
        </div>
      </div>
    </div>
  `
})
export class ProfessorDetailComponent implements OnInit {
  private route = inject(ActivatedRoute);
  private profService = inject(ProfessorService);

  professor = signal<ProfessorResponse | null>(null);

  ngOnInit() {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    if (id) {
      this.profService.getById(id).subscribe(p => this.professor.set(p));
    }
  }
}
