// frontend-angular/src/app/features/dashboard/dashboard.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AuthService } from '../../core/services/auth.service';
import { DashboardService } from '../../core/services/dashboard.service';
import { AdminDashboardResponse, ProfessorDashboardResponse, StudentDashboardResponse } from '../../core/models/models';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';
import { LoadingSpinnerComponent } from '../../shared/components/loading-spinner/loading-spinner.component';
import { EmptyStateComponent } from '../../shared/components/empty-state/empty-state.component';
import { finalize } from 'rxjs';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, PageHeaderComponent, LoadingSpinnerComponent, EmptyStateComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Dashboard"></app-page-header>
      
      <div *ngIf="loading()" class="mt-8 flex justify-center">
        <app-loading-spinner text="Loading dashboard data..."></app-loading-spinner>
      </div>
      
      <div *ngIf="!loading() && !error()" class="mt-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <!-- Admin Cards -->
        <ng-container *ngIf="isAdmin()">
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-blue-500">
            <div class="flex items-center"><div class="text-3xl mr-4">👨‍🎓</div><div><p class="text-sm text-gray-500 font-medium">Total Students</p><p class="text-2xl font-bold text-gray-800">{{ adminStats()?.totalStudents || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-green-500">
            <div class="flex items-center"><div class="text-3xl mr-4">👨‍🏫</div><div><p class="text-sm text-gray-500 font-medium">Professors</p><p class="text-2xl font-bold text-gray-800">{{ adminStats()?.totalProfessors || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-purple-500">
            <div class="flex items-center"><div class="text-3xl mr-4">🏢</div><div><p class="text-sm text-gray-500 font-medium">Departments</p><p class="text-2xl font-bold text-gray-800">{{ adminStats()?.totalDepartments || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-yellow-500">
            <div class="flex items-center"><div class="text-3xl mr-4">📚</div><div><p class="text-sm text-gray-500 font-medium">Active Courses</p><p class="text-2xl font-bold text-gray-800">{{ adminStats()?.activeCourses || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-red-500">
            <div class="flex items-center"><div class="text-3xl mr-4">💰</div><div><p class="text-sm text-gray-500 font-medium">Pending Fees</p><p class="text-2xl font-bold text-gray-800">{{ adminStats()?.pendingFeesCount || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-teal-500">
            <div class="flex items-center"><div class="text-3xl mr-4">✅</div><div><p class="text-sm text-gray-500 font-medium">Attendance Rate</p><p class="text-2xl font-bold text-gray-800">{{ adminStats()?.attendanceRate || 0 }}%</p></div></div>
          </div>
        </ng-container>

        <!-- Professor Cards -->
        <ng-container *ngIf="isProfessor()">
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-blue-500">
            <div class="flex items-center"><div class="text-3xl mr-4">📖</div><div><p class="text-sm text-gray-500 font-medium">Assigned Subjects</p><p class="text-2xl font-bold text-gray-800">{{ profStats()?.assignedSubjects || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-green-500">
            <div class="flex items-center"><div class="text-3xl mr-4">👥</div><div><p class="text-sm text-gray-500 font-medium">Total Students Taught</p><p class="text-2xl font-bold text-gray-800">{{ profStats()?.totalStudentsTaught || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-purple-500">
            <div class="flex items-center"><div class="text-3xl mr-4">📅</div><div><p class="text-sm text-gray-500 font-medium">Recent Attendances</p><p class="text-2xl font-bold text-gray-800">{{ profStats()?.recentAttendances || 0 }}</p></div></div>
          </div>
        </ng-container>

        <!-- Student Cards -->
        <ng-container *ngIf="isStudent()">
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-blue-500">
            <div class="flex items-center"><div class="text-3xl mr-4">🎓</div><div><p class="text-sm text-gray-500 font-medium">Enrolled Courses</p><p class="text-2xl font-bold text-gray-800">{{ studentStats()?.currentEnrolledCourses || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-green-500">
            <div class="flex items-center"><div class="text-3xl mr-4">✅</div><div><p class="text-sm text-gray-500 font-medium">Attendance</p><p class="text-2xl font-bold text-gray-800">{{ studentStats()?.attendancePercentage || 0 }}%</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-red-500">
            <div class="flex items-center"><div class="text-3xl mr-4">💵</div><div><p class="text-sm text-gray-500 font-medium">Pending Fees</p><p class="text-2xl font-bold text-gray-800">$\{{ studentStats()?.pendingFeeAmount || 0 }}</p></div></div>
          </div>
          <div class="bg-white rounded-lg shadow-sm p-6 border-l-4 border-purple-500">
            <div class="flex items-center"><div class="text-3xl mr-4">📝</div><div><p class="text-sm text-gray-500 font-medium">Recent Results</p><p class="text-2xl font-bold text-gray-800">{{ studentStats()?.recentExamResults || 0 }}</p></div></div>
          </div>
        </ng-container>
      </div>

      <div *ngIf="error()" class="mt-6">
        <app-empty-state icon="⚠️" title="Error" [message]="error() || ''"></app-empty-state>
      </div>
    </div>
  `
})
export class DashboardComponent implements OnInit {
  private authService = inject(AuthService);
  private dashboardService = inject(DashboardService);

  loading = signal<boolean>(true);
  error = signal<string | null>(null);

  adminStats = signal<AdminDashboardResponse | null>(null);
  profStats = signal<ProfessorDashboardResponse | null>(null);
  studentStats = signal<StudentDashboardResponse | null>(null);

  isAdmin = signal<boolean>(false);
  isProfessor = signal<boolean>(false);
  isStudent = signal<boolean>(false);

  ngOnInit() {
    this.isAdmin.set(this.authService.hasAnyRole(['ROLE_SUPER_ADMIN', 'ROLE_ADMIN']));
    this.isProfessor.set(this.authService.hasAnyRole(['ROLE_PROFESSOR', 'ROLE_HOD']));
    this.isStudent.set(this.authService.hasRole('ROLE_STUDENT'));

    this.loadDashboardData();
  }

  private loadDashboardData() {
    this.loading.set(true);
    this.error.set(null);

    if (this.isAdmin()) {
      this.dashboardService.getAdminStats().pipe(
        finalize(() => this.loading.set(false))
      ).subscribe({
        next: (data) => this.adminStats.set(data),
        error: (err) => this.error.set('Failed to load admin dashboard data')
      });
    } else if (this.isProfessor()) {
      this.dashboardService.getProfessorStats().pipe(
        finalize(() => this.loading.set(false))
      ).subscribe({
        next: (data) => this.profStats.set(data),
        error: (err) => this.error.set('Failed to load professor dashboard data')
      });
    } else if (this.isStudent()) {
      this.dashboardService.getStudentStats().pipe(
        finalize(() => this.loading.set(false))
      ).subscribe({
        next: (data) => this.studentStats.set(data),
        error: (err) => this.error.set('Failed to load student dashboard data')
      });
    } else {
      this.loading.set(false);
      this.error.set('No dashboard available for your role');
    }
  }
}

// frontend-react/src/features/dashboard/Dashboard.tsx
import React from 'react';
import { useAuth } from '@/features/auth/AuthContext';
import { useQuery } from '@tanstack/react-query';
import { dashboardService } from '@/api/dashboardService';
import { PageHeader } from '@/components/PageHeader';
import { LoadingSpinner } from '@/components/LoadingSpinner';
import { Users, GraduationCap, Building2, BookOpen, DollarSign, BarChart3, ClipboardCheck } from 'lucide-react';

const StatCard = ({ icon: Icon, label, value, colorClass }: { icon: any, label: string, value: string | number, colorClass: string }) => (
  <div className={`bg-white p-6 rounded-lg shadow-sm border-l-4 ${colorClass} flex items-center`}>
    <div className="p-3 rounded-full bg-gray-50 mr-4">
      <Icon className={`w-6 h-6 ${colorClass.replace('border-', 'text-')}`} />
    </div>
    <div>
      <p className="text-sm text-gray-500 font-medium">{label}</p>
      <h3 className="text-2xl font-bold text-gray-900">{value}</h3>
    </div>
  </div>
);

export const Dashboard: React.FC = () => {
  const { user, hasRole, hasAnyRole } = useAuth() as any;
  const isAdmin = hasAnyRole(['SUPER_ADMIN', 'ADMIN']);
  const isProfessor = hasAnyRole(['PROFESSOR', 'HOD']);
  const isStudent = hasRole('STUDENT');

  const { data: adminRes, isLoading: adminLoading } = useQuery({
    queryKey: ['adminDashboard'],
    queryFn: () => dashboardService.getAdminDashboard(),
    enabled: isAdmin,
  });

  const { data: profRes, isLoading: profLoading } = useQuery({
    queryKey: ['professorDashboard'],
    queryFn: () => dashboardService.getProfessorDashboard(),
    enabled: isProfessor,
  });

  const { data: studentRes, isLoading: studentLoading } = useQuery({
    queryKey: ['studentDashboard'],
    queryFn: () => dashboardService.getStudentDashboard(),
    enabled: isStudent,
  });

  if (adminLoading || profLoading || studentLoading) return <LoadingSpinner />;

  const adminData = adminRes?.data;
  const profData = profRes?.data;
  const studentData = studentRes?.data;

  return (
    <div className="space-y-6">
      <PageHeader title={`Welcome back, ${(user as any)?.username || 'User'}!`} />
      
      {isAdmin && adminData && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          <StatCard icon={Users} label="Total Students" value={adminData.totalStudents || 0} colorClass="border-blue-500 text-blue-500" />
          <StatCard icon={GraduationCap} label="Total Professors" value={adminData.totalProfessors || 0} colorClass="border-green-500 text-green-500" />
          <StatCard icon={Building2} label="Total Departments" value={adminData.totalDepartments || 0} colorClass="border-purple-500 text-purple-500" />
          <StatCard icon={BookOpen} label="Active Courses" value={adminData.activeCourses || 0} colorClass="border-indigo-500 text-indigo-500" />
          <StatCard icon={DollarSign} label="Pending Fees" value={`$${adminData.pendingFeesCount || 0}`} colorClass="border-amber-500 text-amber-500" />
          <StatCard icon={BarChart3} label="Attendance Rate" value={`${adminData.attendanceRate || 0}%`} colorClass="border-emerald-500 text-emerald-500" />
        </div>
      )}

      {isProfessor && profData && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <StatCard icon={BookOpen} label="Assigned Subjects" value={profData.assignedSubjects || 0} colorClass="border-indigo-500 text-indigo-500" />
          <StatCard icon={Users} label="Total Students Taught" value={profData.totalStudentsTaught || 0} colorClass="border-blue-500 text-blue-500" />
          <StatCard icon={ClipboardCheck} label="Recent Attendances" value={profData.recentAttendances || 0} colorClass="border-green-500 text-green-500" />
        </div>
      )}

      {isStudent && studentData && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatCard icon={BookOpen} label="Enrolled Courses" value={studentData.currentEnrolledCourses || 0} colorClass="border-indigo-500 text-indigo-500" />
          <StatCard icon={BarChart3} label="Attendance %" value={`${studentData.attendancePercentage || 0}%`} colorClass="border-emerald-500 text-emerald-500" />
          <StatCard icon={DollarSign} label="Pending Fee Amount" value={`$${studentData.pendingFeeAmount || 0}`} colorClass="border-amber-500 text-amber-500" />
          <StatCard icon={ClipboardCheck} label="Recent Exam Results" value={studentData.recentExamResults || 0} colorClass="border-blue-500 text-blue-500" />
        </div>
      )}
    </div>
  );
};
