// frontend-angular/src/app/features/professors/professor-list/professor-list.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ProfessorService } from '../../../core/services/professor.service';
import { DepartmentService } from '../../../core/services/department.service';
import { AuthService } from '../../../core/services/auth.service';
import { ProfessorResponse, DepartmentSummaryResponse } from '../../../core/models/models';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { DataTableComponent } from '../../../shared/components/data-table/data-table.component';
import { ModalComponent } from '../../../shared/components/modal/modal.component';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { finalize } from 'rxjs';

@Component({
  selector: 'app-professor-list',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, PageHeaderComponent, DataTableComponent, ModalComponent, ConfirmDialogComponent, StatusBadgeComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Professors"   (actionClicked)="openCreateModal()"></app-page-header>
      
      <div class="mt-6 bg-white rounded-lg shadow">
        <app-data-table
          [columns]="columns"
          [data]="professors()"
          [totalElements]="0"
          [loading]="loading()"
          (pageChange)="onPageChange($event)"
          >
          <ng-template #cellTemplate let-col let-item>
            <ng-container *ngIf="col.key === 'fullName'">{{ item.firstName }} {{ item.lastName }}</ng-container>
            <ng-container *ngIf="col.key === 'status'"><app-status-badge [status]="item.status"></app-status-badge></ng-container>
            <ng-container *ngIf="col.key === 'actions'">
              <div class="flex space-x-2">
                <a [routerLink]="['/professors', item.id]" class="text-blue-600 hover:text-blue-900">View</a>
                <button *ngIf="isAdminOrDean()" (click)="openEditModal(item)" class="text-indigo-600 hover:text-indigo-900 ml-2">Edit</button>
                <button *ngIf="isAdminOrDean()" (click)="openDeleteConfirm(item)" class="text-red-600 hover:text-red-900 ml-2">Delete</button>
              </div>
            </ng-container>
            <ng-container *ngIf="col.key !== 'fullName' && col.key !== 'status' && col.key !== 'actions'">{{ item[col.key] }}</ng-container>
          </ng-template>
        </app-data-table>
      </div>

      <app-modal [isOpen]="isModalOpen()" [title]="isEditing() ? 'Edit Professor' : 'Add Professor'" (close)="closeModal()">
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4 p-4">
          <div><label class="block text-sm font-medium text-gray-700">Employee ID</label><input type="text" formControlName="employeeId" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm sm:text-sm"></div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">First Name</label><input type="text" formControlName="firstName" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">Last Name</label><input type="text" formControlName="lastName" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">Email</label><input type="email" formControlName="email" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">Phone</label><input type="text" formControlName="phone" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          </div>
          <div><label class="block text-sm">Department</label>
            <select formControlName="departmentId" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">
              <option *ngFor="let dept of departments()" [value]="dept.id">{{ dept.name }}</option>
            </select>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">Designation</label><input type="text" formControlName="designation" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">Specialization</label><input type="text" formControlName="specialization" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          </div>
          <div><label class="block text-sm">Qualification</label><input type="text" formControlName="qualification" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">Joining Date</label><input type="date" formControlName="joiningDate" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">Status</label>
              <select formControlName="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">
                <option value="ACTIVE">ACTIVE</option><option value="INACTIVE">INACTIVE</option><option value="ON_LEAVE">ON_LEAVE</option><option value="RETIRED">RETIRED</option>
              </select>
            </div>
          </div>
          <div class="mt-5 sm:mt-6 sm:flex sm:flex-row-reverse">
            <button type="submit" [disabled]="form.invalid || submitting()" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none sm:ml-3 sm:w-auto sm:text-sm">Save</button>
            <button type="button" (click)="closeModal()" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none sm:mt-0 sm:w-auto sm:text-sm">Cancel</button>
          </div>
        </form>
      </app-modal>

      <app-confirm-dialog [isOpen]="isConfirmOpen()" title="Delete Professor" message="Are you sure you want to delete this professor?" confirmText="Delete" cancelText="Cancel" (confirm)="deleteProfessor()" (cancel)="closeConfirm()"></app-confirm-dialog>
    </div>
  `
})
export class ProfessorListComponent implements OnInit {
  private profService = inject(ProfessorService);
  private deptService = inject(DepartmentService);
  private authService = inject(AuthService);
  private fb = inject(FormBuilder);

  professors = signal<ProfessorResponse[]>([]);
  departments = signal<DepartmentSummaryResponse[]>([]);
  totalElements = signal<number>(0);
  loading = signal<boolean>(false);
  submitting = signal<boolean>(false);
  
  isModalOpen = signal<boolean>(false);
  isConfirmOpen = signal<boolean>(false);
  isEditing = signal<boolean>(false);
  selectedProf = signal<ProfessorResponse | null>(null);

  currentPage = 0;
  pageSize = 10;
  searchQuery = '';

  columns = [
    { key: 'employeeId', label: 'Emp ID' },
    { key: 'fullName', label: 'Full Name' },
    { key: 'email', label: 'Email' },
    { key: 'departmentName', label: 'Department' },
    { key: 'designation', label: 'Designation' },
    { key: 'status', label: 'Status' },
    { key: 'actions', label: 'Actions' }
  ];

  form: FormGroup = this.fb.group({
    employeeId: ['', Validators.required],
    firstName: ['', Validators.required],
    lastName: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    phone: [''],
    departmentId: [null, Validators.required],
    designation: [''],
    specialization: [''],
    qualification: [''],
    joiningDate: [''],
    status: ['ACTIVE']
  });

  isAdminOrDean = signal<boolean>(false);

  ngOnInit() {
    this.isAdminOrDean.set(this.authService.hasAnyRole(['ROLE_SUPER_ADMIN', 'ROLE_ADMIN', 'ROLE_DEAN']));
    this.loadData();
    this.deptService.getAll(0, 100).subscribe(res => this.departments.set(res.content));
  }

  loadData() {
    this.loading.set(true);
    this.profService.getAll(this.currentPage, this.pageSize).pipe(
      finalize(() => this.loading.set(false))
    ).subscribe({
      next: (response) => {
        let content = response.content;
        if (this.searchQuery) {
          content = content.filter(p => (p as any).firstName.toLowerCase().includes(this.searchQuery.toLowerCase()) || (p as any).lastName.toLowerCase().includes(this.searchQuery.toLowerCase()) || p.employeeId.includes(this.searchQuery));
        }
        this.professors.set(content as any[]);
        this.totalElements.set(response.totalElements);
      }
    });
  }

  onPageChange(page: number) { this.currentPage = page; this.loadData(); }
  onSearch(query: string) { this.searchQuery = query; this.currentPage = 0; this.loadData(); }

  openCreateModal() { this.isEditing.set(false); this.form.reset({status: 'ACTIVE'}); this.isModalOpen.set(true); }
  openEditModal(prof: ProfessorResponse) { this.isEditing.set(true); this.selectedProf.set(prof); this.form.patchValue(prof); this.isModalOpen.set(true); }
  closeModal() { this.isModalOpen.set(false); }

  openDeleteConfirm(prof: ProfessorResponse) { this.selectedProf.set(prof); this.isConfirmOpen.set(true); }
  closeConfirm() { this.isConfirmOpen.set(false); }

  onSubmit() {
    if (this.form.invalid) return;
    this.submitting.set(true);
    const request = this.form.value;
    
    const obs = this.isEditing() ? this.profService.update(this.selectedProf()!.id, request) : this.profService.create(request);
    obs.pipe(finalize(() => this.submitting.set(false))).subscribe({
      next: () => { this.closeModal(); this.loadData(); }
    });
  }

  deleteProfessor() {
    const id = this.selectedProf()?.id;
    if (id) {
      this.profService.delete(id).subscribe({ next: () => { this.closeConfirm(); this.loadData(); } });
    }
  }
}

// frontend-react/src/features/professors/ProfessorList.tsx
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useNavigate } from 'react-router-dom';
import { Eye, Pencil, Trash2 } from 'lucide-react';

import { professorService } from '@/api/professorService';
import { departmentService } from '@/api/departmentService';
import { useAuth } from '@/features/auth/AuthContext';
import { useToast } from '@/components/Toast';
import { PageHeader } from '@/components/PageHeader';
import { DataTable, Column } from '@/components/DataTable';
import { Modal } from '@/components/Modal';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { StatusBadge } from '@/components/StatusBadge';
import { FormInput } from '@/components/FormInput';
import { FormSelect } from '@/components/FormSelect';

const professorSchema = z.object({
  firstName: z.string().min(2, 'First name is required'),
  lastName: z.string().min(2, 'Last name is required'),
  email: z.string().email('Invalid email'),
  phone: z.string().min(10, 'Phone is required'),
  employeeId: z.string().min(2, 'Employee ID is required'),
  departmentId: z.coerce.number().min(1, 'Department is required'),
  designation: z.string().min(2, 'Designation is required'),
  specialization: z.string().min(2, 'Specialization is required'),
  qualification: z.string().min(2, 'Qualification is required'),
  joiningDate: z.string().min(1, 'Joining date is required'),
  status: z.enum(['ACTIVE', 'INACTIVE', 'ON_LEAVE', 'RETIRED']),
});

type ProfessorFormValues = z.infer<typeof professorSchema>;

export const ProfessorList: React.FC = () => {
  const { hasAnyRole } = useAuth() as any;
  const toast = useToast();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isAdmin = hasAnyRole(['SUPER_ADMIN', 'ADMIN', 'HOD']);

  const [page, setPage] = useState(0);
  const [size] = useState(10);
  const [search, setSearch] = useState('');
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  const [selectedProf, setSelectedProf] = useState<any>(null);

  const { data, isLoading } = useQuery({
    queryKey: ['professors', page, size, search],
    queryFn: () => search ? professorService.search({ query: search, page, size }) : professorService.getAll({ page, size }),
  });

  const { data: deptRes } = useQuery({
    queryKey: ['departmentsForSelect'],
    queryFn: () => departmentService.getAll({ page: 0, size: 100 }),
  });

  const { register, handleSubmit, reset, formState: { errors } } = useForm<ProfessorFormValues>({
    resolver: zodResolver(professorSchema),
    defaultValues: { status: 'ACTIVE' },
  });

  const createMutation = useMutation({
    mutationFn: (data: ProfessorFormValues) => professorService.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['professors'] });
      toast.success('Professor created');
      setIsModalOpen(false);
      reset();
    },
    onError: () => toast.error('Failed to create professor'),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: ProfessorFormValues }) => professorService.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['professors'] });
      toast.success('Professor updated');
      setIsModalOpen(false);
      reset();
    },
    onError: () => toast.error('Failed to update professor'),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => professorService.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['professors'] });
      toast.success('Professor deleted');
      setIsDeleteModalOpen(false);
    },
    onError: () => toast.error('Failed to delete professor'),
  });

  const onSubmit = (formData: ProfessorFormValues) => {
    if (selectedProf) updateMutation.mutate({ id: selectedProf.id, data: formData });
    else createMutation.mutate(formData);
  };

  const columns: Column<any>[] = [
    { header: 'Emp ID', accessor: 'employeeId' },
    { header: 'First Name', accessor: 'firstName' },
    { header: 'Last Name', accessor: 'lastName' },
    { header: 'Department', accessor: 'departmentName' },
    { header: 'Designation', accessor: 'designation' },
    { header: 'Status', accessor: 'status', render: (item) => <StatusBadge status={item.status as any} /> },
    { header: 'Actions', accessor: 'id', render: (item) => (
        <div className="flex space-x-2">
          <button onClick={() => navigate(`/professors/${item.id}`)} className="text-blue-600"><Eye size={18} /></button>
          {isAdmin && (
            <>
              <button onClick={() => { setSelectedProf(item); reset(item); setIsModalOpen(true); }} className="text-yellow-600"><Pencil size={18} /></button>
              <button onClick={() => { setSelectedProf(item); setIsDeleteModalOpen(true); }} className="text-red-600"><Trash2 size={18} /></button>
            </>
          )}
        </div>
      )
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader title="Professors" action={isAdmin ? <button className="px-4 py-2 bg-blue-600 text-white rounded-md" onClick={() => { setSelectedProf(null); reset({}); setIsModalOpen(true); }}>Add Professor</button> : undefined} />
      
      <div className="bg-white p-4 rounded-lg shadow-sm border">
        <input type="text" placeholder="Search..." className="w-full md:w-1/3 p-2 border rounded-md" value={search} onChange={(e) => setSearch(e.target.value)} />
      </div>

      <DataTable columns={columns} data={data?.data?.content || []} loading={isLoading} page={page} totalPages={data?.data?.totalPages || 0} onPageChange={setPage} />

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={selectedProf ? 'Edit Professor' : 'Add Professor'}>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <FormInput label="First Name" {...register('firstName')} error={errors.firstName?.message} />
            <FormInput label="Last Name" {...register('lastName')} error={errors.lastName?.message} />
            <FormInput label="Email" type="email" {...register('email')} error={errors.email?.message} />
            <FormInput label="Phone" {...register('phone')} error={errors.phone?.message} />
            <FormInput label="Employee ID" {...register('employeeId')} error={errors.employeeId?.message} />
            <FormSelect label="Department" {...register('departmentId')} error={errors.departmentId?.message} options={deptRes?.data?.content?.map((d: any) => ({ value: d.id, label: d.name })) || []} />
            <FormInput label="Designation" {...register('designation')} error={errors.designation?.message} />
            <FormInput label="Specialization" {...register('specialization')} error={errors.specialization?.message} />
            <FormInput label="Qualification" {...register('qualification')} error={errors.qualification?.message} />
            <FormInput label="Joining Date" type="date" {...register('joiningDate')} error={errors.joiningDate?.message} />
            <FormSelect label="Status" {...register('status')} error={errors.status?.message} options={[{value: 'ACTIVE', label: 'Active'}, {value: 'INACTIVE', label: 'Inactive'}, {value: 'ON_LEAVE', label: 'On Leave'}, {value: 'RETIRED', label: 'Retired'}]} />
          </div>
          <div className="flex justify-end space-x-2">
            <button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 border rounded-md">Cancel</button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded-md">Save</button>
          </div>
        </form>
      </Modal>

      <ConfirmDialog isOpen={isDeleteModalOpen} title="Delete Professor" message="Are you sure?" onConfirm={() => deleteMutation.mutate(selectedProf?.id)} onClose={() => setIsDeleteModalOpen(false)} variant="danger" />
    </div>
  );
};
