// frontend-angular/src/app/features/colleges/college-list/college-list.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { CollegeService } from '../../../core/services/college.service';
import { AuthService } from '../../../core/services/auth.service';
import { CollegeResponse } from '../../../core/models/models';
import { PageHeaderComponent } from '../../../shared/components/page-header/page-header.component';
import { DataTableComponent } from '../../../shared/components/data-table/data-table.component';
import { ModalComponent } from '../../../shared/components/modal/modal.component';
import { ConfirmDialogComponent } from '../../../shared/components/confirm-dialog/confirm-dialog.component';
import { StatusBadgeComponent } from '../../../shared/components/status-badge/status-badge.component';
import { finalize } from 'rxjs';

@Component({
  selector: 'app-college-list',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule, PageHeaderComponent, DataTableComponent, ModalComponent, ConfirmDialogComponent, StatusBadgeComponent],
  template: `
    <div class="p-6">
      <app-page-header title="Colleges"   (actionClicked)="openCreateModal()"></app-page-header>
      
      <div class="mt-6 bg-white rounded-lg shadow">
        <app-data-table
          [columns]="columns"
          [data]="colleges()"
          [totalElements]="0"
          [loading]="loading()"
          (pageChange)="onPageChange($event)"
          >
          <ng-template #cellTemplate let-col let-item>
            <ng-container *ngIf="col.key === 'status'">
              <app-status-badge [status]="item.isActive ? 'ACTIVE' : 'INACTIVE'"></app-status-badge>
            </ng-container>
            <ng-container *ngIf="col.key === 'actions'">
              <div class="flex space-x-2">
                <a [routerLink]="['/colleges', item.id]" class="text-blue-600 hover:text-blue-900">View</a>
                <button *ngIf="isAdmin()" (click)="openEditModal(item)" class="text-indigo-600 hover:text-indigo-900 ml-2">Edit</button>
                <button *ngIf="isAdmin()" (click)="openDeleteConfirm(item)" class="text-red-600 hover:text-red-900 ml-2">Delete</button>
              </div>
            </ng-container>
            <ng-container *ngIf="col.key !== 'status' && col.key !== 'actions'">
              {{ item[col.key] }}
            </ng-container>
          </ng-template>
        </app-data-table>
      </div>

      <app-modal [isOpen]="isModalOpen()" [title]="isEditing() ? 'Edit College' : 'Add College'" (close)="closeModal()">
        <form [formGroup]="form" (ngSubmit)="onSubmit()" class="space-y-4 p-4">
          <div><label class="block text-sm font-medium text-gray-700">Name</label><input type="text" formControlName="name" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"></div>
          <div><label class="block text-sm font-medium text-gray-700">Code</label><input type="text" formControlName="code" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"></div>
          <div><label class="block text-sm font-medium text-gray-700">Address</label><input type="text" formControlName="address" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">City</label><input type="text" formControlName="city" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">State</label><input type="text" formControlName="state" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">Country</label><input type="text" formControlName="country" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">Pincode</label><input type="text" formControlName="pincode" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-sm">Phone</label><input type="text" formControlName="phone" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
            <div><label class="block text-sm">Email</label><input type="email" formControlName="email" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          </div>
          <div><label class="block text-sm">Website</label><input type="text" formControlName="website" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          <div><label class="block text-sm">Established Year</label><input type="number" formControlName="establishedYear" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm"></div>
          <div class="flex items-center"><input type="checkbox" formControlName="isActive" class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded"><label class="ml-2 block text-sm text-gray-900">Active</label></div>
          <div class="mt-5 sm:mt-6 sm:flex sm:flex-row-reverse">
            <button type="submit" [disabled]="form.invalid || submitting()" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-indigo-600 text-base font-medium text-white hover:bg-indigo-700 focus:outline-none sm:ml-3 sm:w-auto sm:text-sm">Save</button>
            <button type="button" (click)="closeModal()" class="mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none sm:mt-0 sm:w-auto sm:text-sm">Cancel</button>
          </div>
        </form>
      </app-modal>

      <app-confirm-dialog [isOpen]="isConfirmOpen()" title="Delete College" message="Are you sure you want to delete this college? This action cannot be undone." confirmText="Delete" cancelText="Cancel" (confirm)="deleteCollege()" (cancel)="closeConfirm()"></app-confirm-dialog>
    </div>
  `
})
export class CollegeListComponent implements OnInit {
  private collegeService = inject(CollegeService);
  private authService = inject(AuthService);
  private fb = inject(FormBuilder);

  colleges = signal<CollegeResponse[]>([]);
  totalElements = signal<number>(0);
  loading = signal<boolean>(false);
  submitting = signal<boolean>(false);
  
  isModalOpen = signal<boolean>(false);
  isConfirmOpen = signal<boolean>(false);
  isEditing = signal<boolean>(false);
  selectedCollege = signal<CollegeResponse | null>(null);

  currentPage = 0;
  pageSize = 10;
  searchQuery = '';

  columns = [
    { key: 'name', label: 'Name' },
    { key: 'code', label: 'Code' },
    { key: 'city', label: 'City' },
    { key: 'state', label: 'State' },
    { key: 'status', label: 'Status' },
    { key: 'actions', label: 'Actions' }
  ];

  form: FormGroup = this.fb.group({
    name: ['', Validators.required],
    code: ['', Validators.required],
    address: [''],
    city: [''],
    state: [''],
    country: [''],
    pincode: [''],
    phone: [''],
    email: [''],
    website: [''],
    establishedYear: [''],
    isActive: [true]
  });

  isAdmin = signal<boolean>(false);

  ngOnInit() {
    this.isAdmin.set(this.authService.hasAnyRole(['ROLE_SUPER_ADMIN', 'ROLE_ADMIN']));
    this.loadData();
  }

  loadData() {
    this.loading.set(true);
    this.collegeService.getAll(this.currentPage, this.pageSize).pipe(
      finalize(() => this.loading.set(false))
    ).subscribe({
      next: (response) => {
        let content = response.content;
        if (this.searchQuery) {
          content = content.filter(c => c.name.toLowerCase().includes(this.searchQuery.toLowerCase()) || c.code.toLowerCase().includes(this.searchQuery.toLowerCase()));
        }
        this.colleges.set(content as any);
        this.totalElements.set(response.totalElements);
      }
    });
  }

  onPageChange(page: number) { this.currentPage = page; this.loadData(); }
  onSearch(query: string) { this.searchQuery = query; this.currentPage = 0; this.loadData(); }

  openCreateModal() { this.isEditing.set(false); this.form.reset({isActive: true}); this.isModalOpen.set(true); }
  openEditModal(college: CollegeResponse) { this.isEditing.set(true); this.selectedCollege.set(college); this.form.patchValue(college); this.isModalOpen.set(true); }
  closeModal() { this.isModalOpen.set(false); }

  openDeleteConfirm(college: CollegeResponse) { this.selectedCollege.set(college); this.isConfirmOpen.set(true); }
  closeConfirm() { this.isConfirmOpen.set(false); }

  onSubmit() {
    if (this.form.invalid) return;
    this.submitting.set(true);
    const request = this.form.value;
    
    const obs = this.isEditing() ? this.collegeService.update(this.selectedCollege()!.id, request) : this.collegeService.create(request);
    obs.pipe(finalize(() => this.submitting.set(false))).subscribe({
      next: () => { this.closeModal(); this.loadData(); }
    });
  }

  deleteCollege() {
    const id = this.selectedCollege()?.id;
    if (id) {
      this.collegeService.delete(id).subscribe({ next: () => { this.closeConfirm(); this.loadData(); } });
    }
  }
}

// frontend-react/src/features/colleges/CollegeList.tsx
import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { useNavigate } from 'react-router-dom';
import { Eye, Pencil, Trash2 } from 'lucide-react';

import { collegeService } from '@/api/collegeService';
import { useAuth } from '@/features/auth/AuthContext';
import { useToast } from '@/components/Toast';
import { PageHeader } from '@/components/PageHeader';
import { DataTable, Column } from '@/components/DataTable';
import { Modal } from '@/components/Modal';
import { ConfirmDialog } from '@/components/ConfirmDialog';
import { StatusBadge } from '@/components/StatusBadge';
import { FormInput } from '@/components/FormInput';

const collegeSchema = z.object({
  name: z.string().min(3, 'Name is required'),
  code: z.string().min(2, 'Code is required'),
  address: z.string().min(5, 'Address is required'),
  city: z.string().min(2, 'City is required'),
  state: z.string().min(2, 'State is required'),
  country: z.string().min(2, 'Country is required'),
  pincode: z.string().min(4, 'Pincode is required'),
  phone: z.string().min(10, 'Phone is required'),
  email: z.string().email('Invalid email'),
  website: z.string().url().optional().or(z.literal('')),
  establishedYear: z.coerce.number().min(1800, 'Invalid year').max(new Date().getFullYear()),
  isActive: z.boolean().default(true),
});

type CollegeFormValues = z.infer<typeof collegeSchema>;

export const CollegeList: React.FC = () => {
  const { hasAnyRole } = useAuth() as any;
  const toast = useToast();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const isAdmin = hasAnyRole(['SUPER_ADMIN', 'ADMIN']);

  const [page, setPage] = useState(0);
  const [size] = useState(10);
  const [search, setSearch] = useState('');
  
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false);
  const [selectedCollege, setSelectedCollege] = useState<any>(null);

  const { data, isLoading } = useQuery({
    queryKey: ['colleges', page, size, search],
    queryFn: () => search ? collegeService.search({ query: search, page, size }) : collegeService.getAll({ page, size }),
  });

  const { register, handleSubmit, reset, formState: { errors } } = useForm<CollegeFormValues>({
    resolver: zodResolver(collegeSchema),
  });

  const createMutation = useMutation({
    mutationFn: (data: CollegeFormValues) => collegeService.create(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['colleges'] });
      toast.success('College created successfully');
      setIsModalOpen(false);
      reset();
    },
    onError: () => toast.error('Failed to create college'),
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: number; data: CollegeFormValues }) => collegeService.update(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['colleges'] });
      toast.success('College updated successfully');
      setIsModalOpen(false);
      reset();
    },
    onError: () => toast.error('Failed to update college'),
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => collegeService.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['colleges'] });
      toast.success('College deleted successfully');
      setIsDeleteModalOpen(false);
    },
    onError: () => toast.error('Failed to delete college'),
  });

  const onSubmit = (formData: CollegeFormValues) => {
    if (selectedCollege) {
      updateMutation.mutate({ id: selectedCollege.id, data: formData });
    } else {
      createMutation.mutate(formData);
    }
  };

  const columns: Column<any>[] = [
    { header: 'Name', accessor: 'name' },
    { header: 'Code', accessor: 'code' },
    { header: 'City', accessor: 'city' },
    { header: 'State', accessor: 'state' },
    { header: 'Status', accessor: 'isActive', render: (item) => <StatusBadge status={item.isActive ? 'ACTIVE' : 'INACTIVE'} /> },
    { header: 'Actions', accessor: 'id', render: (item) => (
        <div className="flex space-x-2">
          <button onClick={() => navigate(`/colleges/${item.id}`)} className="text-blue-600 hover:text-blue-800"><Eye size={18} /></button>
          {isAdmin && (
            <>
              <button onClick={() => { setSelectedCollege(item); reset(item); setIsModalOpen(true); }} className="text-yellow-600 hover:text-yellow-800"><Pencil size={18} /></button>
              <button onClick={() => { setSelectedCollege(item); setIsDeleteModalOpen(true); }} className="text-red-600 hover:text-red-800"><Trash2 size={18} /></button>
            </>
          )}
        </div>
      )
    },
  ];

  return (
    <div className="space-y-6">
      <PageHeader 
        title="Colleges" 
        action={isAdmin ? <button className="px-4 py-2 bg-blue-600 text-white rounded-md" onClick={() => { setSelectedCollege(null); reset({}); setIsModalOpen(true); }}>Add College</button> : undefined} 
      />
      
      <div className="bg-white p-4 rounded-lg shadow-sm border">
        <input 
          type="text" 
          placeholder="Search colleges..." 
          className="w-full md:w-1/3 p-2 border rounded-md"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
      </div>

      <DataTable
        columns={columns}
        data={data?.data?.content || []}
        loading={isLoading}
        page={page}
        totalPages={data?.data?.totalPages || 0}
        onPageChange={setPage}
      />

      <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title={selectedCollege ? 'Edit College' : 'Add College'}>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <FormInput label="Name" {...register('name')} error={errors.name?.message} />
            <FormInput label="Code" {...register('code')} error={errors.code?.message} />
            <FormInput label="Address" {...register('address')} error={errors.address?.message} />
            <FormInput label="City" {...register('city')} error={errors.city?.message} />
            <FormInput label="State" {...register('state')} error={errors.state?.message} />
            <FormInput label="Country" {...register('country')} error={errors.country?.message} />
            <FormInput label="Pincode" {...register('pincode')} error={errors.pincode?.message} />
            <FormInput label="Phone" {...register('phone')} error={errors.phone?.message} />
            <FormInput label="Email" type="email" {...register('email')} error={errors.email?.message} />
            <FormInput label="Website" {...register('website')} error={errors.website?.message} />
            <FormInput label="Established Year" type="number" {...register('establishedYear')} error={errors.establishedYear?.message} />
            <div className="flex items-center mt-6">
              <input type="checkbox" id="isActive" {...register('isActive')} className="mr-2" />
              <label htmlFor="isActive" className="ml-2">Is Active</label>
            </div>
          </div>
          <div className="flex justify-end space-x-2">
            <button type="button" onClick={() => setIsModalOpen(false)} className="px-4 py-2 border rounded-md">Cancel</button>
            <button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">Save</button>
          </div>
        </form>
      </Modal>

      <ConfirmDialog
        isOpen={isDeleteModalOpen}
        title="Delete College"
        message={`Are you sure you want to delete ${selectedCollege?.name}?`}
        onConfirm={() => deleteMutation.mutate(selectedCollege?.id)}
        onClose={() => setIsDeleteModalOpen(false)}
        variant="danger"
      />
    </div>
  );
};
